version: '3.8'

services:
  db:
    image: postgres:16
    container_name: app_db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PWD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    container_name: app
    depends_on:
      - db
    build: ./
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:$POSTGRES_PORT/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PWD
      - SPRING_DATASOURCE_DRIVER=$SPRING_DATASOURCE_DRIVER
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data: